Repository re-nolja/FITPET_FRONTEND, pull requests merged in 2021-07, with the labels that each got.

#2 feat : 폴더, 파일 생성
  fitpet/src/App.js
  fitpet/src/pages/ErrorPage.jsx
  fitpet/src/pages/LoginPage.jsx
  fitpet/src/pages/MainPage.jsx
  fitpet/src/pages/NotFoundPage.jsx
  fitpet/src/pages/SignUpPage.jsx
Labels: feature

#15 feat : 로그인 팝업 UI 인터렉션 구현 [#14]
  fitpet/src/components/login/Login.jsx
  fitpet/src/components/login/LoginBottom.jsx
  fitpet/src/components/login/LoginInput.jsx
Labels: feature

#19 feat : 로그인 팝업 UI 포커싱 기능 완료[#18]
  fitpet/src/components/login/LoginInput.jsx
Labels: feature

#20 feat : 회원가입 마지막 단계 스타일 구현 #13
  fitpet/src/components/signUp/SignUp.jsx
  fitpet/src/components/signUp/SignUpBottom.jsx
  fitpet/src/components/signUp/SignUpContent.jsx
  fitpet/src/components/signUp/SignUpEnd.jsx
  fitpet/src/components/signUp/SignUpHeader.jsx
  fitpet/src/components/signUp/SignUpInput.jsx
  fitpet/src/components/signUp/SignUpSocial.jsx
  fitpet/src/pages/SignUpPage.jsx
Labels: feature

#22 feat : input 박스 css 코드 리팩토링, config : 공통 CSS 폴더, 파일 생성 [#13]
  fitpet/src/common/Button.jsx
  fitpet/src/common/Container.jsx
  fitpet/src/common/Font.jsx
  fitpet/src/common/index.jsx
  fitpet/src/components/signUp/SignUp.jsx
  fitpet/src/pages/SignUpPage.jsx
Labels: config, feature

#25 [FEAT] common 컴포넌트 생성하기(버튼, 브레이크포인트)
  fitpet/package-lock.json
  fitpet/package.json
  fitpet/src/assets/theme.jsx
  fitpet/src/common/Button.jsx
  fitpet/src/common/buttons/middle-size/MiddleSizeButton.jsx
  fitpet/src/common/buttons/small-size/IconButton.jsx
  fitpet/src/common/buttons/small-size/ToggleButton.jsx
  fitpet/src/components/login/Login.jsx
  fitpet/src/components/login/LoginInput.jsx
  fitpet/src/index.js
Labels: feature

#27 feat : font h1, 코스페이지 컨텐츠 박스 완료 [#24]
  fitpet/src/App.js
  fitpet/src/common/Container.jsx
  fitpet/src/common/Font.jsx
  fitpet/src/common/contents/CoursePage.jsx
  fitpet/src/common/fonts/Font.jsx
  fitpet/src/common/index.jsx
  fitpet/src/pages/CommonPage.jsx
Labels: feature

#29 메인페이지 커뮤니티 부분 제외 UI 구현 완료.
  fitpet/package-lock.json
  fitpet/package.json
  fitpet/public/img/markerImg.png
  fitpet/src/common/buttons/middle-size/MiddleSizeButton.jsx
  fitpet/src/common/fonts/Font.jsx
  fitpet/src/common/index.jsx
  fitpet/src/common/map/Marker.jsx
  fitpet/src/components/mainpage/banner/Banner.jsx
  fitpet/src/components/mainpage/banner/MainNav.jsx
  fitpet/src/components/mainpage/course/Course.jsx
  fitpet/src/components/mainpage/course/CourseLeft.jsx
  fitpet/src/components/mainpage/course/CourseRight.jsx
  fitpet/src/components/mainpage/header/Header.jsx
  fitpet/src/components/mainpage/header/MemberLinkLi.jsx
  fitpet/src/components/mainpage/header/MemberLinkUl.jsx
  fitpet/src/hooks/useWindowScroll.js
  fitpet/src/pages/MainPage.jsx
Labels: feature

#30 [FEAT] 메인페이지 UI 작업
  fitpet/src/common/buttons/circle/SliderLeftButton.jsx
  fitpet/src/common/buttons/circle/SliderRightButton.jsx
  fitpet/src/common/buttons/middle-size/MiddleSizeButton.jsx
  fitpet/src/common/buttons/small-size/IconButton.jsx
  fitpet/src/common/contents/CoursePage.jsx
  fitpet/src/common/contents/common/Only.jsx
  fitpet/src/common/contents/common/Tag.jsx
  fitpet/src/common/contents/common/WishSmall.jsx
  fitpet/src/common/fonts/Font.jsx
  fitpet/src/common/index.jsx
  fitpet/src/components/mainpage/rentalcars/Rentalcars.jsx
  fitpet/src/components/mainpage/slider/Slider.jsx
  fitpet/src/components/signUp/SignUp.jsx
  fitpet/src/pages/CommonPage.jsx
  fitpet/src/pages/MainPage.jsx
Labels: feature

#34 [FEAT] 메인페이지 작업
  fitpet/src/common/accessibility/Hidden.jsx
  fitpet/src/common/buttons/middle-size/MiddleSizeButton.jsx
  fitpet/src/common/buttons/small-size/GoUpBtn.jsx
  fitpet/src/common/buttons/small-size/IconButton.jsx
  fitpet/src/components/mainpage/banner/Banner.jsx
  fitpet/src/components/mainpage/community/Community.jsx
  fitpet/src/components/mainpage/course/Course.jsx
  fitpet/src/components/mainpage/course/CourseLeft.jsx
  fitpet/src/components/mainpage/header/Header.jsx
  fitpet/src/pages/MainPage.jsx
Labels: feature

#40 feat : 메인페이지 UI 구현 완료
  fitpet/src/common/buttons/small-size/GoUpBtn.jsx
  fitpet/src/common/buttons/small-size/IconButton.jsx
  fitpet/src/components/mainpage/community/Carousel.jsx
  fitpet/src/components/mainpage/community/Community.jsx
Labels: feature

#39 feat : 슬라이드 버튼 활성화 기능 구현 완료 resolved #37
  fitpet/src/components/mainpage/slider/SliderLocation.jsx
  fitpet/src/components/mainpage/slider/SliderOnly.jsx
  fitpet/src/components/mainpage/slider/SliderRentalcar.jsx
Labels: feature

#45 [FEAT] 예약 정보 입력 페이지 UI 구현
  fitpet/src/App.js
  fitpet/src/common/buttons/middle-size/MiddleSizeButton.jsx
  fitpet/src/components/reservation/Agreement.jsx
  fitpet/src/components/reservation/Payment.jsx
  fitpet/src/components/reservation/Reservation.jsx
  fitpet/src/components/reservation/ReservationInput.jsx
  fitpet/src/components/reservation/ReservationSticker.jsx
  fitpet/src/pages/ReservationPage.jsx
Labels: enhancement, feature

#48 [FEAT] 숙소 리스트 페이지 UI 작업
  fitpet/src/App.js
  fitpet/src/common/buttons/small-size/IconButton.jsx
  fitpet/src/common/utility/SmallLine.jsx
  fitpet/src/components/hotel/hotelList/HotelBanner.jsx
  fitpet/src/components/hotel/hotelList/HotelDetails.jsx
  fitpet/src/components/hotel/hotelList/HotelInfo.jsx
  fitpet/src/components/hotel/hotelList/HotelList.jsx
  fitpet/src/components/hotel/hotelList/HotelListHeader.jsx
  fitpet/src/components/hotel/hotelList/HotelTextInfo.jsx
  fitpet/src/components/hotel/hotel_common/HotelSearch.jsx
  fitpet/src/components/reservation/Agreement.jsx
  fitpet/src/components/reservation/ReservationSticker.jsx
  fitpet/src/pages/HotelListPage.jsx
Labels: enhancement, feature

#50 feat : 좌측 필터링 버튼 UI 작업완료[#46]
  fitpet/src/components/hotel/hotelList/DogFilter.jsx
  fitpet/src/components/hotel/hotelList/HotelFilter.jsx
  fitpet/src/components/hotel/hotelList/HotelList.jsx
  fitpet/src/components/hotel/hotelList/LevelFilter.jsx
  fitpet/src/components/hotel/hotelList/RatingFilter.jsx
  fitpet/src/components/hotel/hotel_common/filterCommon.js
Labels: enhancement, feature

#52 [FEAT] 숙소리스트 페이지 UI 인터랙션 작업하기
  fitpet/src/components/hotel/hotelList/HotelBanner.jsx
  fitpet/src/components/hotel/hotelList/HotelFilter.jsx
  fitpet/src/components/hotel/hotelList/HotelInfo.jsx
  fitpet/src/components/hotel/hotelList/HotelList.jsx
  fitpet/src/components/hotel/hotelList/LevelFilter.jsx
  fitpet/src/components/hotel/hotelList/RatingFilter.jsx
  fitpet/src/components/hotel/hotel_common/HotelSearch.jsx
  fitpet/src/components/hotel/hotel_common/filterCommon.js
  fitpet/src/components/mainpage/header/Header.jsx
Labels: enhancement, invalid

#56 [FEAT] 예약 정보 입력페이지 라디오 버튼 커스텀
  fitpet/src/components/hotel/hotelAbout/HotelAbout.jsx
  fitpet/src/components/hotel/hotel_common/filterCommon.js
  fitpet/src/components/hotel/hotel_list/LevelFilter.jsx
  fitpet/src/components/hotel/hotel_list/RatingFilter.jsx
  fitpet/src/components/reservation/Agreement.jsx
  fitpet/src/components/reservation/Payment.jsx
Labels: enhancement, feature

#60 [FEAT] 로그인 페이지 모달창 구현
  fitpet/public/index.html
  fitpet/src/App.js
  fitpet/src/components/login/Login.jsx
  fitpet/src/components/login/LoginHeader.jsx
  fitpet/src/components/login/LoginModal.jsx
  fitpet/src/components/mainpage/header/Header.jsx
  fitpet/src/components/mainpage/header/MemberLinkLi.jsx
  fitpet/src/components/mainpage/header/MemberLinkUl.jsx
  fitpet/src/index.css
  fitpet/src/pages/LoginPage.jsx
  fitpet/src/pages/MainPage.jsx
Labels: enhancement

#63 [FEAT] 리덕스 기본설정
  fitpet/package-lock.json
  fitpet/package.json
  fitpet/src/App.js
  fitpet/src/components/login/Login.jsx
  fitpet/src/components/login/LoginHeader.jsx
  fitpet/src/components/login/LoginModal.jsx
  fitpet/src/components/mainpage/header/Header.jsx
  fitpet/src/redux/modules/index.js
  fitpet/src/redux/store.js
Labels: enhancement, feature

#77 [FEAT] 운전자정보입력 페이지 UI 구현
  fitpet/src/App.js
  fitpet/src/components/driver_info/DriverAgreement.jsx
  fitpet/src/components/driver_info/DriverInfo.jsx
  fitpet/src/components/driver_info/DriverInput.jsx
  fitpet/src/components/driver_info/DriverPayment.jsx
  fitpet/src/components/driver_info/DriverSticky.jsx
  fitpet/src/components/driver_info/LicenseButton.jsx
  fitpet/src/components/reservation/Reservation.jsx
  fitpet/src/pages/DriverInfoPage.jsx
Labels: enhancement, feature

#78 [FIX] 모달창 렌더링시에 뒤에 버튼 가려지는 버그 수정
  fitpet/public/index.html
  fitpet/src/components/common/header/Header.jsx
  fitpet/src/components/login/Login.jsx
  fitpet/src/components/login/LoginModal.jsx
  fitpet/src/components/modal/Modal.jsx
Labels: bug
